pub const TICK_RATE: u64 = 1000; // 1ms

pub const NETWORK_PORT: &str = "127.0.0.1:8000";
pub const NETWORK_READ_TIMEOUT: u64 = 100;
pub const NETWORK_WRITE_TIMEOUT: u64 = 2 * TICK_RATE;
pub const SEQUENCE_NOT_CONFIRMED: u32 = 0;

pub const PACKET_HISTORY_BUFFER_CAPACITY: usize = 1024;

pub const UPLINK_BUFFER_CAPACITY: usize = 64;

pub const LOG_BUFFER_CAPACITY: usize = 8192;

pub const VISIBILITY_WINDOW_LIMIT_MS: u64 = 30 * TICK_RATE;

pub const DECODE_DEADLINE_MS: u64 = 3 * TICK_RATE;
pub const COMMAND_DISPATCH_DEADLINE_MS: u64 = 2 * TICK_RATE;

pub const LOSS_OF_CONTACT_THRESHOLD: u32 = 3;
pub const FAULT_ALERT_THRESHOLD_MS: u64 = 100 * TICK_RATE;

pub const NETWORK_MS: u64 = 2 * TICK_RATE;
pub const COMMAND_MS: u64 = 5 * TICK_RATE;
pub const MONITOR_MS: u64 = 5 * TICK_RATE;
pub const MAIN_MS: u64 = 1000 * TICK_RATE;

pub const MONITOR_PRIORITY: u8 = 10;
pub const NETWORK_PRIORITY: u8 = 5;
pub const COMMAND_PRIORITY: u8 = 4;
pub const LOGGING_PRIORITY: u8 = 0;

pub const MAX_SUBSYSTEM: usize = 2;

pub const SYNC_INTERVAL_WINDOWS: u32 = 1;
pub const SYNC_CALIBRATED_INTERVAL_WINDOWS: u32 = 5;

pub const NUMBER_OF_CORES: u64 = 4;